---
# - name: Import distribution vars
#   ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
#   vars:
#     params:
#       files:
#         - '{{ ansible_distribution }}.yml'
#         - '{{ ansible_os_family }}.yml'
#         - default.yml
#       paths:
#         - 'vars'

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  #with_items: "{{ packages }}"
  when: "ansible_os_family == 'Debian'"

- name: Add public keys to hosts
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  loop: "{{ public_keys }}"

- name: Edit sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - {'regex': '^(# *)?PermitRootLogin', 'line': 'PermitRootLogin prohibit-password'}
    - {'regex': '^(# *)?PubkeyAuthentication', 'line': 'PubkeyAuthentication yes'}
    - {'regex': '^(# *)?ChallengeResponseAuthentication', 'line': 'ChallengeResponseAuthentication no'}
    - {'regex': '^(# *)?UsePAM', 'line': 'UsePAM yes'}
  notify:
    - "Restart sshd"

- name: Remove existing groups from sudoers config
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^(?!%wheel)%.*'

- name: Ensure wheel group in sudoers config
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Create certs file
  ansible.builtin.file:
    path: /etc/openldap/certs/
    state: directory
    mode: '0600'
    owner: root
    group: root
    recurse: true

- name: Copy cert CA
  ansible.builtin.lineinfile:
    path: /etc/openldap/certs/ca.pem
    line: "{{ sssd_ca_cert }}}"
    create: true
    state: present
    mode: '0600'
    owner: root
    group: root

- name: Copy sssd related configs
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item.file }}"
    dest: "{{ item.path }}/{{ item.file }}"
    mode: '0600'
    owner: root
    group: root
  loop:
    - {'file': 'sssd.conf', 'path': '/etc/sssd/'}
    - {'file': 'nsswitch.conf', 'path': '/etc/'}
  notify:
    - Restart sssd
